"""created dispatches table

Revision ID: 43f4b0f1e944
Revises: feef1b627a1c
Create Date: 2023-05-17 21:32:58.426250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f4b0f1e944'
down_revision = 'feef1b627a1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dispatches',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('application_uuid', sa.Uuid(), nullable=True),
    sa.Column('email_uuid', sa.Uuid(), nullable=True),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_uuid'], ['emails.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_uuid'], ['emails.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_Dispatches_uuid'), 'Dispatches', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Dispatches_uuid'), table_name='Dispatches')
    op.drop_table('Dispatches')
    # ### end Alembic commands ###
