"""created dispatches table

Revision ID: aee610e71c9b
Revises: feef1b627a1c
Create Date: 2023-05-20 13:50:32.888701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aee610e71c9b"
down_revision = "feef1b627a1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dispatches",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("application_uuid", sa.Uuid(), nullable=True),
        sa.Column("email_uuid", sa.Uuid(), nullable=True),
        sa.Column("template", sa.String(), nullable=True),
        sa.Column("variables", sa.JSON(), nullable=True),
        sa.Column("logs", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_uuid"], ["emails.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["email_uuid"], ["emails.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_dispatches_uuid"), "dispatches", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dispatches_uuid"), table_name="dispatches")
    op.drop_table("dispatches")
    # ### end Alembic commands ###
