"""setup initial database structure

Revision ID: aeea7f3fc161
Revises: 
Create Date: 2023-04-29 18:47:17.130480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeea7f3fc161'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('layout', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_applications_name'), 'applications', ['name'], unique=False)
    op.create_index(op.f('ix_applications_uuid'), 'applications', ['uuid'], unique=False)
    op.create_table('credentials',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('application_uuid', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_uuid'], ['applications.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_credentials_uuid'), 'credentials', ['uuid'], unique=False)
    op.create_table('emails',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('application_uuid', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_uuid'], ['applications.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_emails_name'), 'emails', ['name'], unique=False)
    op.create_index(op.f('ix_emails_uuid'), 'emails', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_uuid'), table_name='emails')
    op.drop_index(op.f('ix_emails_name'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_credentials_uuid'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_applications_uuid'), table_name='applications')
    op.drop_index(op.f('ix_applications_name'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
