"""added subject column to emails table

Revision ID: b4561dc2553a
Revises: a957c51f8422
Create Date: 2023-05-20 23:30:21.378758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4561dc2553a'
down_revision = 'a957c51f8422'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('subject', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'subject')
    # ### end Alembic commands ###
