"""added getters and setters for template columns

Revision ID: b5b7993e9b93
Revises: b4561dc2553a
Create Date: 2023-05-23 19:47:43.899477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b7993e9b93'
down_revision = 'b4561dc2553a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'layout', nullable=True, new_column_name='_layout')
    op.alter_column('emails', 'template', nullable=False, new_column_name='_template')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', '_layout', nullable=True, new_column_name='layout')
    op.alter_column('emails', '_template', nullable=False, new_column_name='template')
    # ### end Alembic commands ###
